### PR TITLE
feat(vis-type: scatter): selecting points from multiple facets

### PR DESCRIPTION
**Pull request by oltionchampari**
Closes https://github.com/datavisyn/communication_xaira_ordino/issues/30

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- allow selecting points from multiple facets

### Screenshots
gr

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

### CODE REVIEW

**Comment by thinkh** [comment]
> I think we might have to also adapt the selected labels limit as for facets, maybe it should be distributed or copied to all the facets

I get what you mean but I think since the space is already very limited in the facet plots I would not show N labels per plot. 

@dg-datavisyn What do you think about this?

**Review by thinkh — APPROVED** [review]
Very nice implementation. Works as expected in my tests. 

Waiting for feedback (see previous comment).

**Comment by dg-datavisyn** [comment]
> > I think we might have to also adapt the selected labels limit as for facets, maybe it should be distributed or copied to all the facets
> 
> I get what you mean but I think since the space is already very limited in the facet plots I would not show N labels per plot.
> 
> @dg-datavisyn What do you think about this?

From a users point of view, I agree with Olli. The limit should be applied to each facet.  My concerns are, that this requires some additional work on the ticket. So, please deploy this version as is and add it to the [Scatterplot ticket](https://github.com/datavisyn/visyn_core/issues/87)

**Comment by thinkh** [comment]
Thanks, @dg-datavisyn. I've added a task to the related ticket.

**Pull request merged**
