### PR TITLE
refactor(vis-type: bar): use echarts for bar chart

### PR DESCRIPTION
**Pull request by thinkh**
Closes https://github.com/datavisyn/visyn_core/issues/89

### Developer Checklist (Definition of Done)

**Issue**

- [ ] All acceptance criteria from the issue are met
- [ ] Tested in latest Chrome/Firefox

**UI/UX/Vis**

- [ ] Requires UI/UX/Vis review
  - [ ] Reviewer(s) are notified (_tag assignees_)
  - [ ] Review has occurred (_link to notes_)
  - [ ] Feedback is included in this PR
  - [ ] Reviewer(s) approve of concept and design

**Code**

- [ ] Branch is up-to-date with the branch to be merged with, i.e., develop
- [ ] Code is cleaned up and formatted
- [ ] Unit tests are written (frontend/backend if applicable)
- [ ] Integration tests are written (if applicable)

**PR**

- [ ] Descriptive title for this pull request is provided (will be used for release notes later)
- [ ] Reviewer and assignees are defined
- [ ] Add type label (e.g., *bug*, *feature*) to this pull request
- [ ] Add release label (e.g., `release: minor`) to this PR following [semver](https://semver.org/)
- [ ] The PR is connected to the corresponding issue (via `Closes #...`)
- [ ] [Summary of changes](#summary-of-changes) is written

### Summary of changes

- 

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

### CODE REVIEW

**Comment by thinkh** [comment]
The last commit computes the correct data for each facet bar chart.

image

It also works in combination with grouping.

image

**Comment by thinkh** [comment]
Current status with scrollable facets and correct chart height depending on the grouping and facets.

image

image

image

image

**Comment by thinkh** [comment]
Incoming selections are highlighted in the bars

image


Group by numerical columns: values are binned and displayed as categories

image

Tooltip on hover in Mantine colors

image

**Comment by thinkh** [comment]
I truncated the labels of the group axis if they are longer than 50 characters. For the screenshot I reduced the length to 10 characters to show the effect:

image

You can also see that the bar height of non-grouped bars is fixed (and higher now).

**Comment by dg-datavisyn** [comment]
If I open up the bar chart in a freshly loaded tissue workbench, all bars are at 100 %
image

If I switch to a different Aggregate type, e.g. Average, and then back to "Count", then it looks right
image

**Comment by dg-datavisyn** [comment]
Vertical looks weird
image

**Comment by dg-datavisyn** [comment]
Grouping doesn't do anything. The grouping options also list Name (STRING) and Age (NUMERICAL), which I don't know if it makes sense

https://github.com/user-attachments/assets/002bec35-fe7a-4ea7-b9f0-72c48e30f481

**Comment by dg-datavisyn** [comment]
Faceting doesn't work. It only lists the headers
image

**Comment by dg-datavisyn** [comment]
When I click on a bar to select, there is a little "0" visible
image

**Comment by dg-datavisyn** [comment]
When I click on a bar and hover over the others, there is a flickering

https://github.com/user-attachments/assets/0284f38f-0ea5-4c61-b862-f171a2a32e1d

**Comment by dg-datavisyn** [comment]
Sentence case

image

**Comment by dg-datavisyn** [comment]
If we have many categories, the legend overflows and also the numbers overplot. I think we could remove the numbers by default and only show then on hover. I don't know if I needed to scroll down, but the max bar length could be wider
image

**Comment by dg-datavisyn** [comment]
image

**Comment by dg-datavisyn** [comment]
If I set a Group attribute (Gender in this case), the chart is actually stacked instead of grouped. I need to switch to Stacked and then back to grouped to get the actual grouped bar chart
image

then it works
image

**Comment by dv-usama-ansari** [comment]
Closing in favor of #497

**Pull request closed without merging**
