### PR TITLE
deps: Upgrade most python deps to latest

### PR DESCRIPTION
**Pull request by puehringer**
@dvmartinweigl This PR updates most python deps to (nearly) latest, with Pydantic remaining on v1. Please test in one of your applications for compatibility.

In visyn_core, everything seems to run through nicely.

### CODE REVIEW

**Comment by dvmartinweigl** [comment]
> @dvmartinweigl This PR updates most python deps to (nearly) latest, with Pydantic remaining on v1. Please test in one of your applications for compatibility.
> 
> In visyn_core, everything seems to run through nicely.

I tested your branch with the new deps in _bioinsight_ and _hts_hidden_ and didn't encounter any issues.

**Comment by dvtschachinger** [comment]
@puehringer in Marketplace360 fastapi-mail is causing some troubles:

image
image

**Comment by thinkh** [comment]
When I switch Ordino Enterprise to this branch and run `rm -rf .venv && python -m venv .venv && source .venv/bin/activate && make develop`, I get the following errors:

```
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
INFO: pip is looking at multiple versions of black to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of tuspyserver to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of sqlparse to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of ruff to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyright to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of networkx to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of natsort to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flake8-type-checking to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of reprovisyn[develop] to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install apache-superset and reprovisyn because these package versions have conflicting dependencies.

The conflict is caused by:
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.3.5 depends on email-validator<2 and >=1.0.5
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.3.4 depends on email-validator<2 and >=1.0.5
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.3.3 depends on email-validator<2 and >=1.0.5
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.3.2 depends on email-validator<2 and >=1.0.5
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.3.1 depends on email-validator<2 and >=1.0.5
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.3.0 depends on email-validator<2 and >=1.0.5
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.2.1 depends on email-validator<2 and >=1.0.5
    visyn-core 3.1.1.dev0 depends on email_validator>=2.0.0
    flask-appbuilder 4.2.0 depends on email-validator<2 and >=1.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
make: *** [Makefile:46: develop] Error 1
```

@puehringer How do we proceed with the `email-validator`?

**Comment by thinkh** [comment]
I removed the `email_validator` dependency and `make_develop` is successful now.

```
Successfully installed Babel-2.12.1 Flask-Babel-2.0.0 Flask-JWT-Extended-4.5.2 Flask-Limiter-3.3.1 Flask-SQLAlchemy-2.5.1 Mako-1.2.4 MarkupSafe-2.1.3 PyJWT-2.8.0 PySocks-1.7.1 Werkzeug-2.3.6 alembic-1.11.1 amqp-5.1.1 anyio-3.7.1 apache-superset-0.0.0.dev0 apispec-6.3.0 asgiref-3.7.2 async-timeout-4.0.2 attrs-23.1.0 backoff-2.2.1 bcrypt-4.0.1 billiard-4.1.0 black-22.12.0 bleach-3.3.1 boto3-1.28.19 botocore-1.31.19 brotli-1.0.9 cachelib-0.4.1 cachetools-5.3.1 celery-5.3.1 certifi-2023.7.22 cffi-1.15.1 charset-normalizer-3.2.0 classify-imports-4.2.0 click-8.1.6 click-didyoumean-0.3.0 click-plugins-1.1.1 click-repl-0.3.0 colorama-0.4.6 convertdate-2.4.0 cron-descriptor-1.4.0 croniter-1.4.1 cryptography-39.0.2 deepdiff-6.2.3 deprecated-1.2.14 deprecation-2.1.0 dnspython-2.4.1 email-validator-1.3.1 et-xmlfile-1.1.0 exceptiongroup-1.1.2 fastapi-0.100.1 flake8-6.1.0 flake8-type-checking-2.1.2 flask-2.1.3 flask-appbuilder-4.3.5 flask-caching-1.10.1 flask-compress-1.13 flask-cors-4.0.0 flask-login-0.6.0 flask-migrate-3.1.0 flask-smorest-0.42.0 flask-talisman-1.1.0 flask-wtf-1.0.1 fsspec-2023.6.0 func_timeout-4.3.5 geographiclib-2.0 geopy-2.3.0 googleapis-common-protos-1.60.0 graphlib-backport-1.0.3 greenlet-2.0.2 grpcio-1.56.2 gunicorn-21.2.0 h11-0.14.0 hashids-1.3.1 hijri-converter-2.3.1 holidays-0.17.2 httpcore-0.17.3 httptools-0.6.0 httpx-0.24.1 humanize-4.7.0 idna-3.4 importlib-metadata-6.8.0 importlib-resources-6.0.0 iniconfig-2.0.0 isodate-0.6.1 itsdangerous-2.1.2 jinja2-3.1.2 jmespath-1.0.1 json-cfg-0.4.2 jsonschema-4.18.6 jsonschema-specifications-2023.7.1 kombu-5.3.1 korean-lunar-calendar-0.3.1 kwonly-args-1.0.10 limits-3.5.0 markdown-3.4.4 markdown-it-py-3.0.0 marshmallow-3.19.0 marshmallow-enum-1.5.1 marshmallow-sqlalchemy-0.26.1 mccabe-0.7.0 mdurl-0.1.2 mirakuru-2.5.1 msgpack-1.0.5 mypy-extensions-1.0.0 natsort-8.3.1 networkx-2.7.1 nodeenv-1.8.0 numpy-1.23.5 openpyxl-3.1.2 opentelemetry-api-1.19.0 opentelemetry-exporter-otlp-1.19.0 opentelemetry-exporter-otlp-proto-common-1.19.0 opentelemetry-exporter-otlp-proto-grpc-1.19.0 opentelemetry-exporter-otlp-proto-http-1.19.0 opentelemetry-exporter-prometheus-1.12.0rc1 opentelemetry-instrumentation-0.40b0 opentelemetry-instrumentation-asgi-0.40b0 opentelemetry-instrumentation-fastapi-0.40b0 opentelemetry-instrumentation-httpx-0.40b0 opentelemetry-instrumentation-logging-0.40b0 opentelemetry-instrumentation-requests-0.40b0 opentelemetry-instrumentation-sqlalchemy-0.40b0 opentelemetry-instrumentation-system-metrics-0.40b0 opentelemetry-proto-1.19.0 opentelemetry-sdk-1.19.0 opentelemetry-semantic-conventions-0.40b0 opentelemetry-util-http-0.40b0 ordered-set-4.1.0 orjson-3.9.2 outcome-1.2.0 packaging-23.1 pandas-1.5.3 paramiko-3.3.1 parsedatetime-2.6 pathspec-0.11.2 pgsanity-0.2.9 platformdirs-3.10.0 pluggy-1.2.0 polyline-2.0.0 port-for-0.7.1 prison-0.2.1 prometheus-client-0.17.1 prompt-toolkit-3.0.39 protobuf-4.23.4 psutil-5.9.5 psycopg-3.1.9 psycopg2-2.9.6 pyarrow-10.0.1 pyathena-2.25.2 pycodestyle-2.11.0 pycparser-2.21 pydantic-1.10.11 pyflakes-3.1.0 pygments-2.15.1 pymeeus-0.5.12 pynacl-1.5.0 pyparsing-3.1.1 pyright-1.1.309 pytest-7.2.2 pytest-order-1.0.1 pytest-postgresql-5.0.0 pytest-runner-6.0.0 python-dateutil-2.8.2 python-dotenv-1.0.0 python-geohash-0.8.5 python-multipart-0.0.6 pytz-2023.3 pyyaml-6.0.1 redis-4.6.0 referencing-0.30.0 reprovisyn-5.2.1.dev0 requests-2.31.0 rich-13.5.2 rpds-py-0.9.2 ruff-0.0.218 s3transfer-0.6.1 selenium-4.11.2 simplejson-3.19.1 six-1.16.0 slack_sdk-3.21.3 sniffio-1.3.0 sortedcontainers-2.4.0 sqlalchemy-1.4.49 sqlalchemy-utils-0.38.3 sqlparse-0.4.3 sshtunnel-0.4.0 starlette-0.27.0 starlette-context-0.3.6 tabulate-0.8.10 tdp-comments-17.0.1.dev0 tenacity-8.2.2 tomli-2.0.1 trio-0.22.2 trio-websocket-0.10.3 tuspyserver-1.2.1 typing-extensions-4.7.1 tzdata-2023.3 ujson-5.8.0 urllib3-1.26.16 uvicorn-0.23.1 uvloop-0.17.0 vine-5.0.0 visyn-core-3.1.1.dev0 watchfiles-0.19.0 wcwidth-0.2.6 webargs-8.3.0 webencodings-0.5.1 websockets-11.0.3 wrapt-1.15.0 wsproto-1.2.0 wtforms-2.3.3 wtforms-json-0.3.5 xlsxwriter-3.0.9 zipp-3.16.2
```

**Comment by thinkh** [comment]
For Ordino Enterprise, I ran `make test` and tested a bit manually and both were successful.

**Comment by thinkh** [comment]
I tested this branch with Ordino Classic and Coral and couldn't find any issues. So no PR is necessary for the related repos.

**Pull request merged**
