### PR TITLE
fix(vis-type: bar): grouping with zero values

### PR DESCRIPTION
**Pull request by dvdanielamoitzi**
@dv-usama-ansari fixing a grouping issue for the barchart

Found in https://github.com/datavisyn/bioinsight/pull/564#issuecomment-2434939057

### Summary of changes

- added documentation for various interfaces and enums in https://github.com/datavisyn/visyn_core/commit/2062e112cd3abb58be48b22e90a1fd94ad2fa946
- fixed infinity values caused by grouping with zero values

### Additional notes for the reviewer(s)

-  
Thanks for creating this pull request 🤗

### CODE REVIEW

**Comment by dv-usama-ansari** [comment]
The test assertions have been changed in https://github.com/datavisyn/visyn_core/pull/598/commits/1b52b4c3ed3dfeb9cf2d369f293c90e2678ae99b since it is the correct value as compared to the previous changes. Previously, `0` values for `globalDomain` were set to `±Infinity`
- https://github.com/datavisyn/visyn_core/blob/4e489ccb2c4d62c5c7b488f03670ffb8508f623b/src/vis/bar/interfaces/internal/helpers/generate-aggregated-data-lookup.ts#L87
- https://github.com/datavisyn/visyn_core/blob/4e489ccb2c4d62c5c7b488f03670ffb8508f623b/src/vis/bar/interfaces/internal/helpers/generate-aggregated-data-lookup.ts#L91
- https://github.com/datavisyn/visyn_core/blob/4e489ccb2c4d62c5c7b488f03670ffb8508f623b/src/vis/bar/interfaces/internal/helpers/generate-aggregated-data-lookup.ts#L96
- https://github.com/datavisyn/visyn_core/blob/4e489ccb2c4d62c5c7b488f03670ffb8508f623b/src/vis/bar/interfaces/internal/helpers/generate-aggregated-data-lookup.ts#L100

**Comment by dv-usama-ansari** [comment]
When all the values of an aggregation are `0` (not `null` or `undefined`), the bar chart does not show up since it cannot plot bars with `0` width. This happens for the following combination of configuration:
image

Me and @thinkh discussed came to a conclusion that there is unfortunately no way to show a bar with zero width. We should show a message to the user in such a case and prompt him/her to change the aggregation type or column selected

**Review by dv-usama-ansari — DISMISSED** [review]
:green_circle: Thank you for the changes! It looks good from my side. :+1:

**Comment by dv-usama-ansari** [comment]
Added column description in the axis labels as discussed with @dvdanielamoitzi in https://github.com/datavisyn/visyn_core/pull/598/commits/8d91a89ac280ec4ef680e1cb068f1979428f697b

The description could be configured to show based on a new property in the config `showColumnDescriptionText` which defaults to `false`

Screenshot from 2024-10-25 11-34-34

There is some clipping when there is not enough space which can be addressed by adding tooltips
Screenshot from 2024-10-25 11-35-53

Also added documentation for various interfaces and enums in https://github.com/datavisyn/visyn_core/pull/598/commits/2062e112cd3abb58be48b22e90a1fd94ad2fa946

**Review by dvdanielamoitzi — COMMENTED** [review]
Looks good from my side! :100:

**Review by dv-usama-ansari — APPROVED** [review]
Thanks for the changes!

**Pull request merged**
