### PR TITLE
Release v9.1.3

### PR DESCRIPTION
**Pull request by thinkh**
## What's Changed
* refactor: rename data-cy to data-testid by @puehringer in https://github.com/datavisyn/visyn_core/pull/234

**Full Changelog**: https://github.com/datavisyn/visyn_core/compare/v9.1.2...v9.1.3

### CODE REVIEW

**Comment by puehringer** [comment]
@thinkh is this a patch release? Because it would break apps which use this selector directly.

**Comment by thinkh** [comment]
@puehringer Good catch! Should we release it as a major? Do you want to include the PR https://github.com/datavisyn/visyn_core/pull/228 to a major release, too?

**Comment by puehringer** [comment]
@thinkh Are we in a hurry of releasing this? Because if not, we could wait for other major changes and do a major then.

**Comment by thinkh** [comment]
It would block us from continuing with PR https://github.com/datavisyn/reprovisyn/pull/1635 or we have to adapt it later again. But we can adapt accordingly.

**Pull request merged**
